// Excellence Bedding — site içeriği (TR + EN)

const tr = {
  nav: [
    ['#hakkimizda', 'Hakkımızda'],
    ['#teknoloji', 'Uyku Teknolojileri'],
    ['#urunler', 'Yatak Koleksiyonu'],
    ['#konsept', 'Bahçe Konsepti'],
    ['#iletisim', 'İletişim'],
  ],
  hero: {
    titleA: 'Sağlıklı uykunun',
    titleEm: 'zarafetle',
    titleB: 'buluştuğu yer',
    lead: '30 yıllık tecrübe, kesintisiz Ar-Ge ve hijyeni ön planda tutan tasarım anlayışıyla Excellence Bedding; en konforlu uyku deneyimini yaşam alanlarınıza taşıyor.',
    primary: 'Yatak Koleksiyonunu Keşfet',
    ghost: 'Bahçe Konseptini Keşfet',
  },
  about: {
    kicker: 'Hakkımızda',
    titleA: 'Teknolojiyi ve ',
    titleEm: 'doğal konforu',
    titleB: ' aynı yatakta buluşturuyoruz',
    p1: 'Excellence Bedding olarak, 30+ yıllık tecrübemiz ve ürün kalitemizle sizlere en iyi hizmeti sunmaktan gurur duyuyoruz. Müşterilerimize daha kaliteli ürünler sağlamak adına teknolojiyi her zaman yakından takip ediyor, Ar-Ge çalışmalarımıza kesintisiz devam ediyor ve sürekli yenileniyoruz.',
    p2: 'Yataklarımızı tasarlarken hijyen ve konforu ön planda tutuyoruz. Amacımız; sizlere sağlıklı ve en konforlu uyku deneyiminin yanı sıra, yaşam alanlarınız için estetik ve rahat çözümler sunmaktır.',
    stats: [
      ['30+', 'Yıllık Tecrübe'],
      ['7', 'Yatak Koleksiyonu'],
      ['2', 'Üretim & Merkez'],
      ['∞', 'Kesintisiz Ar-Ge'],
    ],
  },
  fabrics: {
    kicker: 'Kumaş Teknolojileri',
    title: 'Teninizle uyum içinde',
    items: [
      {
        title: 'Viscon Kumaş',
        text: 'Özel tuşeli viskon kumaş; ipeksi ve rahat hissiyatıyla teninizle uyumlu yapısı sayesinde uykuya daha kolay geçiş yapmanıza yardımcı olur.',
      },
      {
        title: 'Örme Kumaş',
        text: 'Pamuklu yüzey yaz gecelerini serin geçirmenizi sağlar. Nemi doğal olarak absorbe ederek terlemeyi önler, yatağın nefes almasını sağlar.',
      },
      {
        title: 'Pamuk Kumaş',
        text: 'Nanoteknolojik örme kumaş vücutla temas ettiğinde yumuşak ve rahatsız etmeyen bir hissiyat verir. Konforlu ve derin uyku için idealdir.',
      },
    ],
  },
  products: {
    kicker: 'Koleksiyon',
    title: 'Yatak Serisi',
    sub: 'Her biri belirli bir ihtiyaç için tasarlanmış yedi imza yatak. Kartlara dokunarak teknik detayları ve boyutları inceleyin.',
    items: [
      {
        id: 'ozone-therapy',
        name: 'Ozone Therapy',
        tagline: 'Yenileyen ve onaran bir uyku',
        img: '/assets/products/ozone-therapy/1.jpg',
        gallery: [
          '/assets/products/ozone-therapy/1.jpg',
          '/assets/products/ozone-therapy/2.jpg',
          '/assets/products/ozone-therapy/3.jpg',
          '/assets/products/ozone-therapy/4.jpg',
          '/assets/products/ozone-therapy/5.jpg',
        ],
        accent: '#9a7b6a',
        spring: 'Pocket Spring System',
        firmness: 3,
        heights: [
          { label: 'Yatak Yüksekliği', value: '32 cm (±2)' },
          { label: 'Baza / Ayak', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'Ozone Therapy kumaşı, doğada bulunan ve belli bir enerjiye sahip minerallerin özel bir geometrik yapıda bir araya getirilmesiyle elde edilir. Günlük stres, yoğun iş temposu ve yorgunluğun sebep olduğu vücuttaki iletişim bozukluğunun uyku esnasında düzenlenmesine yardımcı olur. İçerdiği kolajen, cildin elastikiyetini destekler.',
      },
      {
        id: 'bodybalance',
        name: 'BodyBalance',
        tagline: 'Dengeli bir uyku, dengeli bir yaşam',
        img: '/assets/products/bodybalance/1.jpg',
        gallery: [
          '/assets/products/bodybalance/1.jpg',
          '/assets/products/bodybalance/2.jpg',
          '/assets/products/bodybalance/3.jpg',
          '/assets/products/bodybalance/4.jpg',
          '/assets/products/bodybalance/5.jpg',
          '/assets/products/bodybalance/6.jpg',
        ],
        accent: '#7b6c8f',
        spring: 'Pocket Spring System',
        firmness: 2,
        heights: [
          { label: 'Yatak Yüksekliği', value: '32 cm (±2)' },
          { label: 'Baza / Ayak', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'BodyBalance yatağının merkezinde özel mineral teknolojili kumaş yer alır. Doğanın eşsiz minerallerinin bilimsel bir yaklaşımla bir araya getirilmesiyle elde edilen bu kumaş; konsantrasyona destek olmayı, güne daha zinde başlamanızı ve vücudun doğal dengesini korumayı amaçlar. Sadece bir uyku alanı değil, kendinizi daha iyi hissetmenize katkı sağlayan bir teknoloji.',
      },
      {
        id: 'panthenol',
        name: 'Panthenol',
        tagline: 'Dinlendirici bir uyku deneyimi',
        img: '/assets/products/panthenol/1.jpg',
        gallery: [
          '/assets/products/panthenol/1.jpg',
          '/assets/products/panthenol/2.jpg',
          '/assets/products/panthenol/3.jpg',
          '/assets/products/panthenol/4.jpg',
          '/assets/products/panthenol/5.jpg',
        ],
        accent: '#9a7b6a',
        spring: 'Pocket Spring System',
        firmness: 3,
        heights: [
          { label: 'Yatak Yüksekliği', value: '32 cm (±2)' },
          { label: 'Baza / Ayak', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'Provitamin B5 içeren Panthenol Yatak Kumaşı, cilt dostu özel bir kumaştır. Siz uyurken cildinizin bariyerini güçlendirmeye yardımcı olur, derinlemesine nemlenmesine destek verir ve doğal yenilenme sürecine katkı sağlar. Uykunuz sadece dinlendirici olmakla kalmaz, cildiniz için destekleyici bir ritüele dönüşür.',
      },
      {
        id: 'lavender',
        name: 'Lavender Serenity',
        tagline: 'Sakinliğin zamansız ritüeli',
        img: '/assets/products/lavender/1.jpg',
        gallery: [
          '/assets/products/lavender/1.jpg',
          '/assets/products/lavender/2.jpg',
          '/assets/products/lavender/3.jpg',
          '/assets/products/lavender/4.jpg',
          '/assets/products/lavender/5.jpg',
        ],
        accent: '#8266a8',
        spring: 'Pocket Spring System',
        firmness: 3,
        heights: [
          { label: 'Yatak Yüksekliği', value: '32 cm (±2)' },
          { label: 'Baza / Ayak', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'Lavanta ve lavanta yağının aromatik karakterinden ilham alan özel kumaş, Lavender yatağın merkezinde yer alır. Yüzeye entegre edilen mikrokapsüller, lavanta esintisinin kullanım sırasında kademeli olarak hissedilmesini destekler. Nefes alabilen yapısı ve yumuşak dokusuyla günün yoğunluğundan uzaklaşabileceğiniz sakin bir dinlenme ortamı sunar.',
      },
      {
        id: 'anti-aging',
        name: 'Anti-Aging Supreme',
        tagline: 'Yenileyen ve onaran bir uyku',
        img: '/assets/products/anti-aging/1.jpg',
        gallery: [
          '/assets/products/anti-aging/1.jpg',
          '/assets/products/anti-aging/2.jpg',
          '/assets/products/anti-aging/3.jpg',
          '/assets/products/anti-aging/4.jpg',
          '/assets/products/anti-aging/5.jpg',
        ],
        accent: '#9a7b6a',
        spring: 'Pocket Spring System',
        firmness: 3,
        heights: [
          { label: 'Yatak Yüksekliği', value: '32 cm (±2)' },
          { label: 'Baza / Ayak', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'Anti-Aging Supreme yatak kumaşı, doğada bulunan enerji yüklü minerallerin özel bir geometrik düzenle bir araya getirilmesiyle geliştirilmiştir. İçerdiği vitamin kompleksi ile cildi nemlendirir, serbest radikallerden korur ve hücre yenilenmesini destekler. Uyku sırasında vücudun yenilenmesine yardımcı olmak için özel olarak tasarlanmıştır.',
      },
      {
        id: 'manolya',
        name: 'Manolya',
        tagline: 'Güçlü Herkül yay sistemi',
        img: '/assets/products/manolya/1.jpg',
        gallery: [
          '/assets/products/manolya/1.jpg',
          '/assets/products/manolya/2.jpg',
          '/assets/products/manolya/3.jpg',
          '/assets/products/manolya/4.jpg',
        ],
        accent: '#9a7b6a',
        spring: 'Herkül Yay Sistemi',
        firmness: 4,
        heights: [
          { label: 'Yatak Yüksekliği', value: '30 cm (±2)' },
          { label: 'Baza / Ayak', value: '27 cm / 10 cm' },
        ],
        sizes: ['90x190', '100x200', '120x200', '150x200', '160x200', '180x200'],
        desc: 'Manolya Set, Excellence Bedding tarafından özel olarak geliştirilen güçlü Herkül yay sistemi ve sabit ped katmanıyla üstün bir konfor sunar. Yüksek dayanım ve doğru omurga desteği için mükemmel uyum ve destek sağlayacak şekilde tasarlanmıştır.',
      },
      {
        id: 'optimal',
        name: 'Optimal',
        tagline: 'Şıklık ve ileri uyku teknolojisi',
        img: '/assets/products/optimal/1.jpg',
        gallery: [
          '/assets/products/optimal/1.jpg',
          '/assets/products/optimal/2.jpg',
          '/assets/products/optimal/3.jpg',
          '/assets/products/optimal/4.jpg',
        ],
        accent: '#5f6b8a',
        spring: 'Herkül Yay Sistemi',
        firmness: 4,
        heights: [
          { label: 'Yatak Yüksekliği', value: '30 cm (±2)' },
          { label: 'Baza / Ayak', value: '27 cm / 12 cm' },
        ],
        sizes: ['90x190', '100x200', '120x200', '150x200', '160x200', '180x200'],
        desc: 'Göz kamaştıran tasarımı ve uyumlu renkleriyle yatak odanıza şıklık katarken, barındırdığı ileri uyku teknolojileriyle uyku sağlığınızı destekler. Herkül Yay Sistemi sayesinde hareket geçişlerini minimuma indirirken, omurganıza özel geliştirilmiş destekleyici yapısıyla her sabaha dinlenmiş olarak uyanmanızı sağlar.',
      },
    ],
  },
  concept: {
    kicker: 'Bahçe Konsepti',
    title: 'Konfor, dış mekâna taşınıyor',
    sub: 'Metal gövdeli dış mekân koleksiyonu; dayanıklılığı ve konforu her mevsim bir arada sunar.',
    features: [
      'Su İtici Kumaş',
      'Ultraviyole (UV) Koruma',
      'Paslanmaya Karşı Dayanıklı',
      'Sıcağa Dayanıklı',
      'Soğuğa Dayanıklı',
      'Darbeye Dayanıklı',
      'Antistatik',
      'Dış Mekan Kumaşı',
      'Elektrostatik Toz Boya',
      'Kolay Demonte',
    ],
    items: [
      {
        name: 'Space Swing',
        img: '/assets/swing.jpeg',
        text: 'Metal iskeletli, tek kişilik konforlu dış mekân koltuğu. Antrasit ve Kapuçino şasi renk seçenekleriyle her bahçeye uyum sağlar.',
        colors: ['Antrasit', 'Kapuçino'],
      },
      {
        name: 'Gondol',
        img: '/assets/gondol.jpeg',
        text: 'Tenteli, çok kişilik salıncak gondol. Dış mekân kumaşı ve elektrostatik toz boyalı gövdesiyle her mevsim dayanıklılık sunar.',
        colors: ['Antrasit', 'Kapuçino'],
      },
    ],
  },
  cta: {
    titleA: 'Kaliteli uyku bir tercih değil,',
    titleEm: 'bir yatırımdır.',
    button: 'Bize Ulaşın',
  },
  contact: {
    info: 'Excellence Bedding Ürün özellikleri, fiyatları ve diğer bilgiler önceden bildirilmeksizin değiştirilebilir.',
    contactTitle: 'İLETİŞİM',
    web: 'www.excellence.tr',
    email: 'info@excellence.tr',
    phones: [
      { label: 'İstanbul Bölge', no: '+90 542 503 12 04' },
      { label: 'Kayseri Bölge', no: '+90 (352) 322 25 22' },
    ],
    offices: [
      {
        city: 'İSTANBUL',
        address: 'Adnan Kahveci Mah. Avrupa Caddesi No:22\nBeylikdüzü / İstanbul / TÜRKİYE',
      },
      {
        city: 'KAYSERİ',
        address: 'Organize San. Böl. 20. Cd No:58\nHacılar / Kayseri / TÜRKİYE',
      },
    ],
    rightsA: 'Excellence Bedding. Tüm hakları saklıdır.',
    rightsB: 'Sağlıklı ve konforlu uyku için tasarlandı.',
  },
  ui: {
    menu: 'Menü',
    details: 'Detayları gör →',
    enlarge: 'Büyüt →',
    close: 'Kapat',
    soft: 'Yumuşak',
    firm: 'Sert',
    sizes: 'Üretim Boyutları',
    colors: 'Renk Seçenekleri',
    features: 'Özellikler',
    photo: 'fotoğraf',
    prev: 'Önceki fotoğraf',
    next: 'Sonraki fotoğraf',
    chooseTitle: 'Dil seçin',
    chooseSub: 'Devam etmek için lütfen dilinizi seçin',
  },
}

const en = {
  nav: [
    ['#hakkimizda', 'About'],
    ['#teknoloji', 'Sleep Technologies'],
    ['#urunler', 'Mattress Collection'],
    ['#konsept', 'Garden Concept'],
    ['#iletisim', 'Contact'],
  ],
  hero: {
    titleA: 'Where healthy sleep',
    titleEm: 'meets elegance',
    titleB: '',
    lead: 'With 30 years of experience, uninterrupted R&D and a design approach that puts hygiene first, Excellence Bedding brings the most comfortable sleep experience into your living spaces.',
    primary: 'Explore the Mattress Collection',
    ghost: 'Explore the Garden Concept',
  },
  about: {
    kicker: 'About',
    titleA: 'Bringing technology and ',
    titleEm: 'natural comfort',
    titleB: ' together in one mattress',
    p1: 'At Excellence Bedding, we are proud to offer you the best service with our 30+ years of experience and product quality. To provide our customers with better products, we always follow technology closely, continue our R&D work without interruption, and constantly renew ourselves.',
    p2: 'When designing our mattresses, we prioritize hygiene and comfort. Our goal is to offer you a healthy and most comfortable sleep experience, along with aesthetic and cozy solutions for your living spaces.',
    stats: [
      ['30+', 'Years of Experience'],
      ['7', 'Mattress Collection'],
      ['2', 'Production & HQ'],
      ['∞', 'Nonstop R&D'],
    ],
  },
  fabrics: {
    kicker: 'Fabric Technologies',
    title: 'In harmony with your skin',
    items: [
      {
        title: 'Viscon Fabric',
        text: 'Special-touch viscose fabric; with its silky, comfortable feel that harmonizes with your skin, it helps you drift into sleep more easily.',
      },
      {
        title: 'Knitted Fabric',
        text: 'A cotton surface keeps you cool on summer nights. By naturally absorbing moisture, it prevents sweating and lets the mattress breathe.',
      },
      {
        title: 'Cotton Fabric',
        text: 'Nanotechnological knitted fabric feels soft and non-irritating against the body. Ideal for comfortable, deep sleep.',
      },
    ],
  },
  products: {
    kicker: 'Collection',
    title: 'Mattress Collection',
    sub: 'Seven signature mattresses, each designed for a specific need. Tap the cards to explore technical details and dimensions.',
    items: [
      {
        id: 'ozone-therapy',
        name: 'Ozone Therapy',
        tagline: 'Sleep that renews and restores',
        img: '/assets/products/ozone-therapy/1.jpg',
        gallery: [
          '/assets/products/ozone-therapy/1.jpg',
          '/assets/products/ozone-therapy/2.jpg',
          '/assets/products/ozone-therapy/3.jpg',
          '/assets/products/ozone-therapy/4.jpg',
          '/assets/products/ozone-therapy/5.jpg',
        ],
        accent: '#9a7b6a',
        spring: 'Pocket Spring System',
        firmness: 3,
        heights: [
          { label: 'Mattress Height', value: '32 cm (±2)' },
          { label: 'Base / Leg', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'Ozone Therapy fabric is created by bringing together minerals found in nature, each carrying a specific energy, in a special geometric structure. It helps regulate the disruption in the body caused by daily stress, intense work pace and fatigue while you sleep. The collagen it contains supports skin elasticity.',
      },
      {
        id: 'bodybalance',
        name: 'BodyBalance',
        tagline: 'Balanced sleep, balanced life',
        img: '/assets/products/bodybalance/1.jpg',
        gallery: [
          '/assets/products/bodybalance/1.jpg',
          '/assets/products/bodybalance/2.jpg',
          '/assets/products/bodybalance/3.jpg',
          '/assets/products/bodybalance/4.jpg',
          '/assets/products/bodybalance/5.jpg',
          '/assets/products/bodybalance/6.jpg',
        ],
        accent: '#7b6c8f',
        spring: 'Pocket Spring System',
        firmness: 2,
        heights: [
          { label: 'Mattress Height', value: '32 cm (±2)' },
          { label: 'Base / Leg', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: "At the heart of the BodyBalance mattress lies a fabric with special mineral technology. Created by bringing nature's unique minerals together with a scientific approach, this fabric aims to support concentration, help you start the day feeling refreshed, and protect the body's natural balance. More than just a place to sleep — a technology that helps you feel better.",
      },
      {
        id: 'panthenol',
        name: 'Panthenol',
        tagline: 'A truly restful sleep experience',
        img: '/assets/products/panthenol/1.jpg',
        gallery: [
          '/assets/products/panthenol/1.jpg',
          '/assets/products/panthenol/2.jpg',
          '/assets/products/panthenol/3.jpg',
          '/assets/products/panthenol/4.jpg',
          '/assets/products/panthenol/5.jpg',
        ],
        accent: '#9a7b6a',
        spring: 'Pocket Spring System',
        firmness: 3,
        heights: [
          { label: 'Mattress Height', value: '32 cm (±2)' },
          { label: 'Base / Leg', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'Panthenol mattress fabric with provitamin B5 is a special skin-friendly fabric. While you sleep, it helps strengthen your skin barrier, supports deep moisturization, and contributes to its natural renewal process. Your sleep becomes more than rest — a ritual that cares for your skin.',
      },
      {
        id: 'lavender',
        name: 'Lavender Serenity',
        tagline: 'The timeless ritual of calm',
        img: '/assets/products/lavender/1.jpg',
        gallery: [
          '/assets/products/lavender/1.jpg',
          '/assets/products/lavender/2.jpg',
          '/assets/products/lavender/3.jpg',
          '/assets/products/lavender/4.jpg',
          '/assets/products/lavender/5.jpg',
        ],
        accent: '#8266a8',
        spring: 'Pocket Spring System',
        firmness: 3,
        heights: [
          { label: 'Mattress Height', value: '32 cm (±2)' },
          { label: 'Base / Leg', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'A special fabric inspired by the aromatic character of lavender and lavender oil lies at the heart of the Lavender mattress. Microcapsules integrated into the surface gradually release a lavender breeze as you use it. With its breathable structure and soft touch, it offers a calm resting space away from the intensity of the day.',
      },
      {
        id: 'anti-aging',
        name: 'Anti-Aging Supreme',
        tagline: 'Sleep that renews and restores',
        img: '/assets/products/anti-aging/1.jpg',
        gallery: [
          '/assets/products/anti-aging/1.jpg',
          '/assets/products/anti-aging/2.jpg',
          '/assets/products/anti-aging/3.jpg',
          '/assets/products/anti-aging/4.jpg',
          '/assets/products/anti-aging/5.jpg',
        ],
        accent: '#9a7b6a',
        spring: 'Pocket Spring System',
        firmness: 3,
        heights: [
          { label: 'Mattress Height', value: '32 cm (±2)' },
          { label: 'Base / Leg', value: '27 cm / 12 cm' },
        ],
        sizes: ['120x200', '150x200', '160x200', '180x200'],
        desc: 'Anti-Aging Supreme mattress fabric is developed by arranging energy-charged minerals found in nature in a special geometric order. With its vitamin complex, it moisturizes the skin, protects it from free radicals, and supports cell renewal. Specially designed to help the body regenerate during sleep.',
      },
      {
        id: 'manolya',
        name: 'Manolya',
        tagline: 'Powerful Hercules spring system',
        img: '/assets/products/manolya/1.jpg',
        gallery: [
          '/assets/products/manolya/1.jpg',
          '/assets/products/manolya/2.jpg',
          '/assets/products/manolya/3.jpg',
          '/assets/products/manolya/4.jpg',
        ],
        accent: '#9a7b6a',
        spring: 'Hercules Spring System',
        firmness: 4,
        heights: [
          { label: 'Mattress Height', value: '30 cm (±2)' },
          { label: 'Base / Leg', value: '27 cm / 10 cm' },
        ],
        sizes: ['90x190', '100x200', '120x200', '150x200', '160x200', '180x200'],
        desc: 'The Manolya Set offers superior comfort with the powerful Hercules spring system developed exclusively by Excellence Bedding and its fixed pad layer. It is designed to provide perfect harmony and support for high durability and correct spinal support.',
      },
      {
        id: 'optimal',
        name: 'Optimal',
        tagline: 'Elegance meets advanced sleep technology',
        img: '/assets/products/optimal/1.jpg',
        gallery: [
          '/assets/products/optimal/1.jpg',
          '/assets/products/optimal/2.jpg',
          '/assets/products/optimal/3.jpg',
          '/assets/products/optimal/4.jpg',
        ],
        accent: '#5f6b8a',
        spring: 'Hercules Spring System',
        firmness: 4,
        heights: [
          { label: 'Mattress Height', value: '30 cm (±2)' },
          { label: 'Base / Leg', value: '27 cm / 12 cm' },
        ],
        sizes: ['90x190', '100x200', '120x200', '150x200', '160x200', '180x200'],
        desc: 'While adding elegance to your bedroom with its dazzling design and harmonious colors, its advanced sleep technologies support your sleep health. Thanks to the Hercules Spring System, it minimizes motion transfer, while its specially developed supportive structure for your spine lets you wake up refreshed every morning.',
      },
    ],
  },
  concept: {
    kicker: 'Garden Concept',
    title: 'Comfort moves outdoors',
    sub: 'A metal-frame outdoor collection offering durability and comfort together in every season.',
    features: [
      'Water-Repellent Fabric',
      'Ultraviolet (UV) Protection',
      'Rust Resistant',
      'Heat Resistant',
      'Cold Resistant',
      'Impact Resistant',
      'Antistatic',
      'Outdoor Fabric',
      'Electrostatic Powder Coating',
      'Easy Assembly',
    ],
    items: [
      {
        name: 'Space Swing',
        img: '/assets/swing.jpeg',
        text: 'A comfortable single metal-frame outdoor chair. With Anthracite and Cappuccino chassis color options, it suits every garden.',
        colors: ['Anthracite', 'Cappuccino'],
      },
      {
        name: 'Gondol',
        img: '/assets/gondol.jpeg',
        text: 'A canopied multi-person swing gondola. With outdoor fabric and an electrostatic powder-coated frame, it offers durability in every season.',
        colors: ['Anthracite', 'Cappuccino'],
      },
    ],
  },
  cta: {
    titleA: 'Quality sleep is not a choice,',
    titleEm: 'but an investment.',
    button: 'Contact Us',
  },
  contact: {
    info: 'Excellence Bedding product features, prices and other information are subject to change without prior notice.',
    contactTitle: 'CONTACT',
    web: 'www.excellence.tr',
    email: 'info@excellence.tr',
    phones: [
      { label: 'Istanbul Region', no: '+90 542 503 12 04' },
      { label: 'Kayseri Region', no: '+90 (352) 322 25 22' },
    ],
    offices: [
      {
        city: 'ISTANBUL',
        address: 'Adnan Kahveci Dist. Avrupa Street No:22\nBeylikdüzü / Istanbul / TURKEY',
      },
      {
        city: 'KAYSERI',
        address: 'Organized Ind. Zone 20th St. No:58\nHacılar / Kayseri / TURKEY',
      },
    ],
    rightsA: 'Excellence Bedding. All rights reserved.',
    rightsB: 'Designed for healthy, comfortable sleep.',
  },
  ui: {
    menu: 'Menu',
    details: 'See details →',
    enlarge: 'Enlarge →',
    close: 'Close',
    soft: 'Soft',
    firm: 'Firm',
    sizes: 'Available Sizes',
    colors: 'Color Options',
    features: 'Features',
    photo: 'photo',
    prev: 'Previous photo',
    next: 'Next photo',
    chooseTitle: 'Choose your language',
    chooseSub: 'Please select a language to continue',
  },
}

export const content = { tr, en }
export const LANG_KEY = 'excellence-lang'
